#!/usr/bin/env python3
"""Generate the nine phase typography compositions (compositions/pNN-*.html).

Each phase is a Studio clip in index.html. Its typography is laid out from the
locked storyboard v2 (screen coords, 1080x1920) and shifted onto where Romeow
actually stands in the 3D world (his feet sit on the ring at y 1333, ~55 px lower
than in the sketches). Every animation is timed from the clip's own start, and the
exit is keyed to the clip's duration, so retiming a clip in Studio keeps it intact.
"""
import pathlib

ROOT = pathlib.Path(__file__).parent
INK, HI, PAPER, CARD = "#2B4C7E", "#F7D154", "#F6F1E7", "#FFFDF7"
DY = 55  # sketch -> world offset for cat-relative typography

FONTS = """
      @font-face { font-family: "Fraunces"; src: url("assets/fonts/Fraunces-latin-var.woff2") format("woff2"); font-weight: 100 900; }
      @font-face { font-family: "Caveat"; src: url("assets/fonts/Caveat-latin-var.woff2") format("woff2"); font-weight: 400 700; }
      @font-face { font-family: "Space Mono"; src: url("assets/fonts/SpaceMono-Regular.woff2") format("woff2"); font-weight: 400; }
      @font-face { font-family: "Space Mono"; src: url("assets/fonts/SpaceMono-Bold.woff2") format("woff2"); font-weight: 700; }"""


def T(x, y, s, size, family="d", anchor="start", fill=INK, extra=""):
    fam = {
        "d": 'font-family="Fraunces" font-weight="900"',
        "d7": 'font-family="Fraunces" font-weight="700"',
        "di": 'font-family="Fraunces" font-weight="700" font-style="italic"',
        "h": 'font-family="Caveat" font-weight="700"',
        "m": 'font-family="Space Mono" font-weight="700" letter-spacing="4"',
    }[family]
    return f'<text x="{x}" y="{y}" {fam} font-size="{size}" text-anchor="{anchor}" fill="{fill}" {extra}>{s}</text>'


class Comp:
    def __init__(self, cid, phase, slug, default_dur):
        self.cid, self.phase, self.slug, self.dur = cid, phase, slug, default_dur
        self.layers = []

    def L(self, name, inner, ox=540, oy=960, wrap=None, style=""):
        el = (
            f'<div class="L" id="{self.cid}-{name}" data-layout-allow-overlap style="transform-origin:{ox}px {oy}px;{style}">'
            f'<svg viewBox="0 0 1080 1920">{inner}</svg></div>'
        )
        self.layers.append(el)
        return el

    def html(self, js):
        c = self.cid
        return f"""<!doctype html>
<html lang="id">
  <head>
    <meta charset="UTF-8" />
    <!-- Generated by build-phases.py — phase {self.phase}: {self.slug}. Edit the generator, not this file. -->
  </head>
  <body>
    <template>
      <style>{FONTS}
        #{c}-root {{
          position: absolute;
          inset: 0;
          perspective: 1400px;
          perspective-origin: 540px 960px;
        }}
        #{c}-root .L {{
          position: absolute;
          left: 0;
          top: 0;
          width: 1080px;
          height: 1920px;
        }}
        #{c}-root .L svg {{
          display: block;
          width: 100%;
          height: 100%;
          overflow: visible;
        }}
        #{c}-root .shadow {{
          filter: drop-shadow(10px 16px 0 rgba(43, 76, 126, 0.18));
        }}
      </style>

      <div id="{c}-root" data-composition-id="{c}" data-width="1080" data-height="1920">
        {"".join(self.layers)}
      </div>

      <script>
        (function () {{
          const CID = "{c}";
          const $ = (n) => document.getElementById(CID + "-" + n);
          // the script's document is scoped to this composition: walk up to our own clip in index.html
          const anyEl = document.querySelector("#{c}-root .L") || document.querySelector(".L");
          const host = anyEl ? anyEl.closest("[data-phase]") : null;
          const D = host ? parseFloat(host.getAttribute("data-duration")) : {self.dur};
          const X = Math.max(D - 0.75, 1.2); // exit: fold away before the camera leaves
          const tl = gsap.timeline({{ paused: true }});
          function popIn(el, t, d) {{
            tl.fromTo(el, {{ rotationX: -95, opacity: 0 }}, {{ rotationX: 0, opacity: 1, duration: d || 0.6, ease: "back.out(1.7)" }}, t);
          }}
          function write(el, t, d, x0, x1) {{
            tl.fromTo(
              el,
              {{ clipPath: `inset(0px ${{1080 - x0}}px 0px 0px)` }},
              {{ clipPath: `inset(0px ${{Math.max(0, 1080 - x1)}}px 0px 0px)`, duration: d, ease: "power1.inOut" }},
              t,
            );
          }}
          function foldOut(els, t) {{
            tl.to(els, {{ rotationX: 95, opacity: 0, duration: 0.35, ease: "power2.in", stagger: 0.03 }}, t);
          }}
{js}
          tl.seek(tl.duration(), true).seek(0, true);
          window.__timelines[CID] = tl;
        }})();
      </script>
    </template>
  </body>
</html>
"""


def folio(c, n):
    c.L("folio", T(100, 300, f"GBR. 1.3 · FASE {n}/7", 30, "m"), 100, 300)


PHASES = []

# ---------------- P01 · pembuka (overview) ----------------
c = Comp("p01", 1, "pembuka", 3)
c.L("bab", T(540, 330, "BAB 3 · MAKHLUK HIDUP DI SEKITAR KITA", 34, "m", "middle"), 540, 330)
c.L("cap1", T(540, 1400, "Gambar 1.3 Siklus hidup Romeow.", 40, "di", "middle"), 540, 1400)
c.L("cap2", T(540, 1462, "catatan: fase 1 paling lama", 48, "h", "middle", extra='opacity="0.85"'), 540, 1462)
PHASES.append((c, """
          // already on screen at t = 0 (loop frame); folds away as the camera dives
          const out = Math.max(D - 1.55, 0.6);
          foldOut([$("cap2"), $("cap1"), $("bab")], out);
"""))

# ---------------- P02 · ① Hibernasi ----------------
c = Comp("p02", 2, "hibernasi", 3.5)
folio(c, 1)
c.L("tidur", T(110, 470, "tidur", 76, "h"), 110, 470)
c.L("hi", f'<rect x="96" y="500" width="610" height="150" fill="{HI}" transform="rotate(-2 400 575)"/>', 96, 575)
c.L("num", T(110, 630, "12–16", 190), 110, 630)
c.L("jam", T(730, 560, "jam", 80, "h"), 730, 560)
c.L("sehari", T(730, 640, "sehari", 80, "h"), 730, 640)
c.L("z1", T(300, 920 + DY, "z", 60, extra='opacity="0.5"'), 315, 900 + DY)
c.L("z2", T(240, 840 + DY, "z", 84, extra='opacity="0.7"'), 260, 815 + DY)
c.L("z3", T(170, 750 + DY, "Z", 110), 200, 715 + DY, style="filter: drop-shadow(6px 10px 0 rgba(43,76,126,0.18))")
arc = "M470,1045 Q760,770 1050,1065"
letters = "Hibernasi Harian"
tsp = "".join(f'<tspan id="p02-a{i}">{ch if ch != " " else "&#160;"}</tspan>' for i, ch in enumerate(letters))
c.L("arc", f'<path id="p02-arcpath" d="{arc}" fill="none"/>'
    f'<text font-family="Fraunces" font-weight="900" font-size="74" fill="{INK}"><textPath href="#p02-arcpath" startOffset="50%" text-anchor="middle">{tsp}</textPath></text>',
    760, 960)
c.L("fact", T(110, 1470, "fase terpanjang — ekor jadi selimut", 56, "h", extra='opacity="0.9"'), 110, 1470)
PHASES.append((c, f"""
          popIn($("folio"), 0.45, 0.5);
          // title letters settle over his back like a blanket, then breathe with him
          tl.set($("arc"), {{ opacity: 1 }}, 0);
          for (let i = 0; i < {len(letters)}; i++) {{
            tl.fromTo(document.getElementById("p02-a" + i), {{ attr: {{ "fill-opacity": 0 }} }}, {{ attr: {{ "fill-opacity": 1 }}, duration: 0.18 }}, 0.55 + i * 0.035);
          }}
          const breaths = Math.max(1, Math.floor((X - 0.5) / 1.1));
          for (let i = 0; i < breaths; i++) {{
            tl.to($("arc"), {{ scale: 1.025, y: -6, duration: 0.55, ease: "sine.inOut" }}, 0.5 + i * 1.1);
            tl.to($("arc"), {{ scale: 1, y: 0, duration: 0.55, ease: "sine.inOut" }}, 1.05 + i * 1.1);
          }}
          // the Z trail leaves his nose and grows into the fact
          [["z1", 0.5], ["z2", 0.75], ["z3", 1.0]].forEach(([n, t]) => {{
            tl.fromTo($(n), {{ opacity: 0, scale: 0.3, x: 60, y: 90 }}, {{ opacity: 1, scale: 1, x: 0, y: 0, duration: 0.55, ease: "back.out(2)" }}, t);
          }});
          tl.to([$("z1"), $("z2"), $("z3")], {{ y: -16, duration: 0.9, ease: "sine.inOut", yoyo: true, repeat: 1, stagger: 0.15 }}, 1.6);
          write($("tidur"), 1.2, 0.4, 100, 300);
          popIn($("num"), 1.35, 0.6);
          tl.fromTo($("hi"), {{ scaleX: 0 }}, {{ scaleX: 1, duration: 0.45, ease: "power3.out" }}, 1.65);
          write($("jam"), 1.8, 0.25, 720, 860);
          write($("sehari"), 1.95, 0.35, 720, 960);
          write($("fact"), 2.05, 0.6, 100, 1000);
          foldOut([$("fact"), $("arc"), $("z3"), $("z2"), $("z1"), $("sehari"), $("jam"), $("num"), $("hi"), $("tidur"), $("folio")], X);
"""))

# ---------------- P03 · ② Peregangan ----------------
c = Comp("p03", 3, "peregangan", 3)
folio(c, 2)
Y3 = 40
c.L("hi", f'<rect x="96" y="{660 + Y3}" width="900" height="150" fill="{HI}"/>', 96, 735 + Y3)
c.L("per", T(120, 620 + Y3, "Peregangan", 104), 540, 840)
c.L("ek", T(546, 790 + Y3, "EKSTREM", 150, anchor="middle"), 546, 735 + Y3)
c.L("meas", T(546, 880 + Y3, "|←—— 1.6× ——→|", 32, "m", "middle", extra='opacity="0.75"'), 546, 870 + Y3)
c.L("fact", T(110, 1470, "melancarkan aliran darah", 60, "h"), 110, 1470)
PHASES.append((c, """
          popIn($("folio"), 0.45, 0.5);
          // the words run along his stretched back (-11°) and stretch with him
          gsap.set([$("per"), $("hi"), $("ek"), $("meas")], { rotation: -11 });
          tl.fromTo($("per"), { x: -420, opacity: 0 }, { x: 0, opacity: 1, duration: 0.55, ease: "power3.out" }, 0.4);
          popIn($("ek"), 0.45, 0.45);
          tl.fromTo($("hi"), { scaleX: 0 }, { scaleX: 0.72, duration: 0.35, ease: "power2.out" }, 0.5);
          tl.to($("ek"), { scaleX: 1.5, duration: 0.7, ease: "power2.out" }, 0.55);
          tl.to($("hi"), { scaleX: 1, duration: 0.7, ease: "power2.out" }, 0.55);
          tl.fromTo($("meas"), { opacity: 0, scaleX: 0.4 }, { opacity: 1, scaleX: 1, duration: 0.4, ease: "back.out(2)" }, 1.1);
          const back = Math.min(2.0, D - 0.9);
          tl.to($("ek"), { scaleX: 1, duration: 0.6, ease: "elastic.out(1, 0.45)" }, back);
          tl.to($("hi"), { scaleX: 0.72, duration: 0.6, ease: "elastic.out(1, 0.45)" }, back);
          tl.to($("meas"), { opacity: 0, scaleX: 0.4, duration: 0.3, ease: "power2.in" }, back);
          write($("fact"), 1.45, 0.55, 100, 820);
          foldOut([$("fact"), $("ek"), $("hi"), $("per"), $("folio")], X);
"""))

# ---------------- P04 · ③ Alarm 05.00 ----------------
c = Comp("p04", 4, "alarm", 3.5)
folio(c, 3)
c.L("t0", T(850, 476, "04.59", 72, "m", "middle", extra='letter-spacing="0"'), 850, 450)
c.L("t1", T(850, 476, "05.00", 72, "m", "middle", extra='letter-spacing="0"'), 850, 450)
c.L("ring", '<path id="p04-ringpath" d="M685,450 A165,165 0 0 1 1015,450" fill="none"/>'
    f'<text font-family="Fraunces" font-weight="900" font-size="50" letter-spacing="5" fill="{INK}"><textPath href="#p04-ringpath" startOffset="50%" text-anchor="middle">ALARM JAM</textPath></text>',
    850, 450)
c.L("m1", T(470, 1010 + DY, "meow", 60, extra=f'opacity="0.55" transform="rotate(-22 470 {1010 + DY})"'), 470, 990 + DY)
c.L("m2", T(520, 930 + DY, "MEOW", 96, extra=f'opacity="0.8" transform="rotate(-18 520 {930 + DY})"'), 540, 900 + DY)
c.L("bub", f'<g transform="rotate(-12 430 {700 + DY})"><rect x="90" y="{610 + DY}" width="680" height="170" rx="24" fill="{CARD}" stroke="{INK}" stroke-width="8"/>'
    + T(430, 750 + DY, "MEOW!", 160, anchor="middle") + "</g>", 430, 700 + DY, style="filter: drop-shadow(10px 16px 0 rgba(43,76,126,0.18))")
c.L("fact", T(110, 1470, "paling aktif saat fajar &amp; senja", 60, "h"), 110, 1470)
PHASES.append((c, f"""
          popIn($("folio"), 0.4, 0.5);
          tl.fromTo($("ring"), {{ opacity: 0, rotation: -40 }}, {{ opacity: 1, rotation: 0, duration: 0.6, ease: "back.out(1.6)" }}, 0.3);
          // flip-clock: 04.59 folds away, 05.00 flips in
          tl.set($("t0"), {{ opacity: 1 }}, 0);
          tl.fromTo($("t0"), {{ rotationX: 0 }}, {{ rotationX: 90, duration: 0.18, ease: "power2.in" }}, 0.55);
          tl.set($("t0"), {{ opacity: 0 }}, 0.73);
          tl.fromTo($("t1"), {{ rotationX: -90, opacity: 0 }}, {{ rotationX: 0, opacity: 1, duration: 0.3, ease: "back.out(2)" }}, 0.73);
          // three meows burst from his mouth toward the lens, each bigger than the last
          const MX = 300, MY = 1032;
          [["m1", 0.55, 300, 0.25], ["m2", 1.25, 450, 0.2], ["bub", 1.95, 700, 0.12]].forEach(([n, t, z, s0]) => {{
            tl.fromTo($(n), {{ opacity: 0, x: MX - 470, y: MY - 1000, z: -z, scale: s0 }}, {{ opacity: 1, x: 0, y: 0, z: 0, scale: 1, duration: 0.45, ease: "back.out(1.8)" }}, t);
          }});
          tl.to($("bub"), {{ rotation: 2.5, duration: 0.06, ease: "none", yoyo: true, repeat: 5 }}, 2.4);
          write($("fact"), 2.2, 0.5, 100, 900);
          foldOut([$("fact"), $("bub"), $("m2"), $("m1"), $("t1"), $("ring"), $("folio")], X);
"""))

# ---------------- P05 · ④ Makan 3 Suap ----------------
c = Comp("p05", 5, "makan", 3.5)
folio(c, 4)
c.L("makan", T(110, 470, "Makan", 120), 110, 470)
c.L("suap", T(730, 760, "Suap", 120), 730, 760)
KRIUK = [("k", 700, 1060, -18), ("r", 750, 1020, 10), ("i", 800, 1050, -6), ("u", 840, 1010, 16), ("k", 890, 1045, -12)]
for i, (ch, x, y, r) in enumerate(KRIUK):
    c.L(f"k{i}", T(x, y, ch, 64, "h", extra=f'transform="rotate({r} {x} {y})"'), x, y)
for i, n in enumerate(["100", "99", "98", "97"]):
    c.L(f"n{i}", T(750, 1314, f"sisa: {n}%", 44, "m", "middle", extra='letter-spacing="1"'), 750, 1300)
c.L("ring", f'<ellipse id="p05-ell" cx="750" cy="1300" rx="170" ry="52" fill="none" stroke="{INK}" stroke-width="5" '
    'transform="rotate(-4 750 1300)" stroke-dasharray="820" stroke-dashoffset="820" stroke-linecap="round"/>', 750, 1300)
c.L("fact", T(110, 1470, "porsi kecil, tapi sering", 60, "h"), 110, 1470)
PHASES.append((c, """
          popIn($("folio"), 0.4, 0.5);
          popIn($("makan"), 0.45, 0.6);
          popIn($("suap"), 0.7, 0.6);
          // counter on the bowl ticks down once per chew (chews at 0.45 / 0.95 / 1.45)
          tl.fromTo($("n0"), { opacity: 0, scale: 0.6 }, { opacity: 1, scale: 1, duration: 0.35, ease: "back.out(2)" }, 0.35);
          const chews = [0.59, 1.09, 1.59];
          chews.forEach((t, i) => {
            tl.set($("n" + i), { opacity: 0 }, t);
            tl.fromTo($("n" + (i + 1)), { opacity: 0, y: -18 }, { opacity: 1, y: 0, duration: 0.25, ease: "bounce.out" }, t);
          });
          // k-r-i-u-k crumbs fly out of the bowl on each chew
          [[0, 0], [1, 0], [2, 1], [3, 2], [4, 2]].forEach(([k, chew]) => {
            tl.fromTo($("k" + k), { opacity: 0, x: -40, y: 170, scale: 0.4 }, { opacity: 1, x: 0, y: 0, scale: 1, duration: 0.45, ease: "back.out(2.4)" }, chews[chew] + k * 0.04);
          });
          tl.to(document.getElementById("p05-ell"), { attr: { "stroke-dashoffset": 0 }, duration: 0.5, ease: "power2.inOut" }, 1.85);
          write($("fact"), 2.1, 0.5, 100, 720);
          foldOut([$("fact"), $("ring"), $("n3"), $("k4"), $("k3"), $("k2"), $("k1"), $("k0"), $("suap"), $("makan"), $("folio")], X);
"""))

# ---------------- P06 · ⑤ Zoomies ----------------
c = Comp("p06", 6, "zoomies", 3.5)
folio(c, 5)
TRAIL = [("Z", -10, 1190, 150, 0.18, 1.9), ("O", 110, 1165, 160, 0.3, 1.7), ("O", 250, 1145, 170, 0.45, 1.5),
         ("M", 380, 1130, 180, 0.6, 1.35), ("I", 530, 1122, 190, 0.75, 1.2), ("E", 590, 1122, 200, 0.9, 1.0), ("S", 700, 1126, 210, 1.0, 1.0)]
inner = []
for i, (ch, x, y, s, op, sx) in enumerate(TRAIL):
    y += DY + 240  # trail runs along the floor under the airborne cat
    inner.append(
        f'<div class="L" id="p06-z{i}" data-layout-allow-overlap style="transform-origin:{x}px {y}px" data-sx="{sx}" data-op="{op}"><svg viewBox="0 0 1080 1920">'
        + T(x, y, ch, s, extra='font-style="italic"') + "</svg></div>"
    )
c.layers.append('<div class="L" id="p06-trail" style="transform-origin:540px 1300px">' + "".join(inner) + "</div>")
c.L("hi", f'<rect x="80" y="{560 + DY}" width="760" height="120" fill="{HI}"/>', 80, 620 + DY)
c.L("cap", T(110, 650 + DY, "melepas energi berlebih!", 84, "h"), 540, 1055)
PHASES.append((c, f"""
          popIn($("folio"), 0.4, 0.5);
          gsap.set([$("trail"), $("hi"), $("cap")], {{ rotation: -9 }});
          gsap.set($("hi"), {{ transformOrigin: "80px {620 + DY}px" }});
          // Z-O-O-M-I-E-S peel off Romeow and trail behind him, stretched like motion blur
          const Z = Array.from(document.querySelectorAll("#p06-trail > .L"));
          Z.forEach((el, i) => {{
            const sx = Number(el.dataset.sx), op = Number(el.dataset.op);
            tl.fromTo(el, {{ opacity: 0, x: 700 - i * 60, scaleX: 0.2 }}, {{ opacity: op, x: 0, scaleX: sx, duration: 0.5, ease: "power3.out" }}, 0.5 + (Z.length - 1 - i) * 0.07);
          }});
          const jit = Math.max(0, Math.floor((X - 1.6) / 0.16));
          for (let j = 0; j < jit; j++) {{
            tl.to(Z, {{ y: (j % 2 ? 1 : -1) * 8, duration: 0.08, ease: "sine.inOut", stagger: 0.01 }}, 1.3 + j * 0.16);
          }}
          tl.to(Z, {{ y: 0, duration: 0.08 }}, 1.3 + jit * 0.16);
          tl.fromTo($("hi"), {{ scaleX: 0 }}, {{ scaleX: 1, duration: 0.4, ease: "power3.out" }}, 0.55);
          write($("cap"), 0.7, 0.55, 100, 900);
          // sudden stop: the trail snaps back to full, crisp letters
          tl.to(Z, {{ scaleX: 1, opacity: 1, duration: 0.18, ease: "power4.out", stagger: 0.015 }}, X - 0.3);
          foldOut([$("cap"), $("hi"), $("trail"), $("folio")], X);
"""))

# ---------------- P07 · ⑥ Eksperimen Gravitasi ----------------
c = Comp("p07", 7, "gravitasi", 3.5)
folio(c, 6)
c.L("eks", T(110, 480, "Eksperimen", 120), 110, 480)
c.L("q", T(120, 570, "naluri pemburu: “ini hidup?”", 60, "h"), 120, 570)
c.L("arrow", f'<path id="p07-arrow" d="M690,610 C760,680 760,780 715,880 M690,860 L714,884 L742,862" fill="none" stroke="{INK}" stroke-width="7" '
    'stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="420" stroke-dashoffset="420"/>', 700, 700)
FALL = [("G", 950, 985, 12), ("R", 960, 1040, 34), ("A", 966, 1095, 58), ("V", 970, 1150, 86), ("I", 972, 1201, 112),
        ("T", 970, 1253, 140), ("A", 964, 1305, 170), ("S", 950, 1355, 196), ("I", 932, 1401, 224)]
for i, (ch, x, y, r) in enumerate(FALL):
    c.L(f"g{i}", T(x, y, ch, 62, anchor="middle", extra=f'transform="rotate({r} {x} {y - 20})"'), x, y - 20)
c.L("tink", T(780, 1455, "tink!", 66, "h", extra='transform="rotate(-8 830 1440)"'), 830, 1440)
PHASES.append((c, """
          popIn($("folio"), 0.4, 0.5);
          popIn($("eks"), 0.45, 0.6);
          write($("q"), 0.75, 0.55, 110, 900);
          tl.to(document.getElementById("p07-arrow"), { attr: { "stroke-dashoffset": 0 }, duration: 0.45, ease: "power2.out" }, 1.0);
          // G-R-A-V-I-T-A-S-I tumbles down the glass's fall line (glass leaves the table at 1.4)
          for (let i = 0; i < 9; i++) {
            tl.fromTo($("g" + i), { opacity: 0, x: -20, y: -(40 + i * 52), rotation: -30 }, { opacity: 1, x: 0, y: 0, rotation: 0, duration: 0.32, ease: "power2.in" }, 1.45 + i * 0.055);
          }
          tl.fromTo($("tink"), { opacity: 0, scale: 0.3 }, { opacity: 1, scale: 1, duration: 0.3, ease: "back.out(3)" }, 2.03);
          // held frame: nothing moves until the exit
          foldOut([$("tink"), $("g8"), $("g7"), $("g6"), $("g5"), $("g4"), $("g3"), $("g2"), $("g1"), $("g0"), $("arrow"), $("q"), $("eks"), $("folio")], X);
"""))

# ---------------- P08 · ⑦ Masuk Kardus ----------------
c = Comp("p08", 8, "kardus", 3.5)
folio(c, 7)
c.L("masuk", T(200, 560, "masuk", 90, "h"), 200, 560)
c.L("arrow", f'<path id="p08-arrow" d="M330,600 C380,720 400,830 440,930 M414,906 L442,934 L462,900" fill="none" stroke="{INK}" stroke-width="7" '
    'stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="420" stroke-dashoffset="420"/>', 400, 760)
c.L("tag", f'<path d="M820,1110 L862,760" stroke="{INK}" stroke-width="4"/>'
    f'<g transform="rotate(8 860 700)"><path d="M700,560 H990 V780 H700 L660,670 Z" fill="{CARD}" stroke="{INK}" stroke-width="6" stroke-linejoin="round"/>'
    f'<circle cx="690" cy="670" r="9" fill="none" stroke="{INK}" stroke-width="4"/>'
    + T(840, 648, "ruang sempit", 54, "h", "middle") + T(840, 722, "= merasa aman", 54, "h", "middle") + "</g>",
    820, 1110, style="filter: drop-shadow(10px 16px 0 rgba(43,76,126,0.18))")
c.L("stamp", T(545, 1250, "KARDUS", 104, anchor="middle", fill="#5E4424", extra='letter-spacing="2"')
    + T(545, 1318, "ISI: 1 KUCING (XL)", 32, "m", "middle", fill="#3D2A14", extra='letter-spacing="1"'), 545, 1240)
PHASES.append((c, """
          popIn($("folio"), 0.4, 0.5);
          write($("masuk"), 0.35, 0.4, 190, 420);
          tl.to(document.getElementById("p08-arrow"), { attr: { "stroke-dashoffset": 0 }, duration: 0.4, ease: "power2.out" }, 0.55);
          // rubber stamp lands after the box stops wobbling
          tl.fromTo($("stamp"), { opacity: 0, scale: 1.7, rotation: -9 }, { opacity: 1, scale: 1, rotation: -3, duration: 0.18, ease: "power4.in" }, 0.7);
          tl.to($("stamp"), { x: 3, duration: 0.05, yoyo: true, repeat: 3, ease: "none" }, 0.88);
          // luggage tag pops up and swings on its string
          tl.fromTo($("tag"), { opacity: 0, rotationX: -95 }, { opacity: 1, rotationX: 0, duration: 0.55, ease: "back.out(1.7)" }, 1.0);
          const swings = Math.max(1, Math.floor((X - 1.6) / 0.6));
          for (let i = 0; i < swings; i++) {
            tl.to($("tag"), { rotation: i % 2 ? -3 : 3, duration: 0.6, ease: "sine.inOut" }, 1.5 + i * 0.6);
          }
          tl.to($("tag"), { rotation: 0, duration: 0.3, ease: "sine.out" }, 1.5 + swings * 0.6);
          foldOut([$("tag"), $("stamp"), $("arrow"), $("masuk"), $("folio")], X);
"""))

# ---------------- P09 · penutup (back to the overview; ends on the t = 0 frame) ----------------
c = Comp("p09", 9, "penutup", 3)
c.L("bab", T(540, 330, "BAB 3 · MAKHLUK HIDUP DI SEKITAR KITA", 34, "m", "middle"), 540, 330)
c.L("cap1", T(540, 1400, "Gambar 1.3 Siklus hidup Romeow.", 40, "di", "middle"), 540, 1400)
c.L("cap2", T(540, 1462, "catatan: fase 1 paling lama", 48, "h", "middle", extra='opacity="0.85"'), 540, 1462)
PHASES.append((c, """
          // write the caption back in and hold it: the last frame matches p01's first frame
          popIn($("bab"), Math.max(D - 1.5, 0.3), 0.5);
          write($("cap1"), Math.max(D - 1.2, 0.5), 0.55, 250, 830);
          write($("cap2"), Math.max(D - 0.75, 0.9), 0.5, 290, 790);
"""))


def main():
    for comp, js in PHASES:
        path = ROOT / "compositions" / f"{comp.cid}-{comp.slug}.html"
        path.write_text(comp.html(js))
        print("wrote", path.name)


if __name__ == "__main__":
    main()
